author: Fluxus Desgin
description: >-
  Um blog sobre boas práticas de usabilidade.
baseurl: ""
url: "https://fluxus-design.github.io"

minima:
  date_format: "%d %B, %Y"

  # Generate social links in footer
  social_links:
    github: fluxus-design

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

lang: "pt-br"

sass:
  sass_dir: _sass
  style: compressed

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      permalink: "/:categories/:title"
      image: assets/images/blog-logo.jpg
