# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Fernanda Bertola
email: febertola.luiz@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Um blog pessoal e portfólio de uma desenvolvedora web.
  Aqui você encontrará as melhores práticas de desenvolvimento
  e notícias sobre o mundo front-end.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://febertola.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Show excerpts on the homepage
show_excerpts: true

minima:
  date_format: "%d %B, %Y"

  # Generate social links in footer
  social_links:
    github: febertola
    linkedin: fernandabertola

header_pages:
  - blog/blog.md
  - pages/portfolio.md

# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

navigation:
  -
    text: Todos
    url: /
    tag: all
  -
    text: Infra
    url: /infra/
    tag: infra
  -
    text: Javascript
    url: /javascript/
    tag: javascript

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

defaults:
  -
    scope:
      path: ""
    values:
      author: "Fernanda Bertola"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      img:
        url: "../../assets/images/blog-logo.jpg"
        alt: "Logo do blog da Fernanda Bertola"
  -
    scope:
      path: "_posts/infra"
    values:
      categories: "infra"
      permalink: "/:categories/:title.html"
  -
    scope:
      path: "_posts/javascript"
    values:
      categories: "javascript"
      permalink: "/:categories/:title.html"

lang: "pt-br"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
